name: CD_PIPELINE
on:
  push:
    branches:
      - develop
jobs:
  development-job:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Check the Repo
        uses: actions/checkout@v2
      - name: Pull Docker Image
        run: docker pull ahsan108art/ucp-notice-board:latest
      - name: Deploy the changes
        run: curl -X POST ${{ secrets.RENDER_CALLBACK_URL }}